const $=s=>document.querySelector(s);let busy=false,fresh=false,cues=[],connected=false,lastCatalogue=0,controlList=2,revision;
const valid=()=>/^\d{1,5}(?:\.\d{1,3})?$/.test($('#cue').value);
function update(){const c=cues.find(c=>c.list===controlList&&Number(c.number)===Number($('#cue').value));$('#cue-name').textContent=$('#cue').value?c?.name||'':'';$('#go').disabled=busy||!connected||!valid();}
document.querySelectorAll('[data-key]').forEach(b=>b.addEventListener('click',()=>{if(busy)return;let s=$('#cue').value,k=b.dataset.key;if(k==='back'){s=s.slice(0,-1);fresh=false;}else{if(fresh)s='';fresh=false;if(k==='.'&&s.includes('.'))return;if(s.length<9)s+=k==='.'&&!s?'0.':k;}$('#cue').value=s;$('#result').textContent='';update();}));
$('#cue').addEventListener('beforeinput',e=>{if(fresh&&e.inputType.startsWith('insert')){$('#cue').value='';fresh=false;}});
$('#cue').addEventListener('input',()=>{fresh=false;$('#result').textContent='';update();});
$('#go').addEventListener('click',async()=>{if(busy||!valid()||!connected)return;const cue=$('#cue').value;busy=true;$('#cue').disabled=true;update();$('#result').textContent='Sending…';try{const r=await fetch('/api/eos/goto',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cue,revision}),signal:AbortSignal.timeout(8000)});const p=await r.json();if(!r.ok)throw Error(p.error||'Send failed');$('#result').textContent=`Sent: cue ${p.list}/${cue}`;fresh=true;}catch(e){$('#result').textContent=e.name==='TimeoutError'?'No reply. Check Eos before retrying.':e.message;}finally{busy=false;$('#cue').disabled=false;update();}});
async function poll(){try{const s=await(await fetch('/api/state',{signal:AbortSignal.timeout(3000)})).json();if(Date.now()-lastCatalogue>15000){cues=await(await fetch('/api/cues')).json();lastCatalogue=Date.now();}controlList=s.settings.controlList;revision=s.settings.revision;document.querySelector('label[for=cue]').textContent='Go to cue · List '+controlList;$('#go').textContent='Go to cue · List '+controlList;connected=s.eos.connected&&Date.now()-s.eos.lastReceived<15000;const c=s.eos.lists[controlList].current;$('#current').textContent=connected?(c?`Current: ${controlList}/${c.number} · ${c.name}`:'No active cue in list '+controlList):'Eos disconnected';}catch{connected=false;$('#current').textContent='Server disconnected';}update();setTimeout(poll,1000);}fetch('/api/cues').then(r=>r.json()).then(c=>{cues=c;update();}).catch(()=>{});poll();

